services:
  - type: web
    name: stock-price-prediction-and-forecasting
    env: python
    buildCommand: ""
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.13